spring:
  application:
    name: Gate-System

  datasource:
    url: "jbdc:mysql://localhost:3306/gatesys?createDatabaseIfNotExists=true"
    username: "root"
    password: "root"

  jpa:
    hibernate:
      ddl-auto: create
